#!/bin/bash

# profile executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.

# set PATH so it includes private bin if it exists
[[ -d "$HOME/.local/bin" ]] && PATH="$HOME/.local/bin:$PATH"
[[ -d "$HOME/.local/bin/statusbar" ]] && PATH="$HOME/.local/bin/statusbar:$PATH"

# programs
export TERMINAL='st'
export TERM='st'
export BROWSER='zen'
export EDITOR='nvim'
export SHELL='zsh'

# XDG base dir specification. check https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export GIT_CONFIG_GLOBAL="$XDG_CONFIG_HOME/git/gitconfig"
export GIT_CREDENTIAL_STORE="$XDG_DATA_HOME/git/credentials"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export MOZ_USE_XINPUT2=1        # Mozilla smooth scrolling/touchpads.

# history files
export LESSHISTFILE="$XDG_CACHE_HOME/less_history"
export PYTHON_HISTORY="$XDG_DATA_HOME/python/history"

export FZF_DEFAULT_OPTS="--style minimal --color 16 --layout=reverse --height 30% --preview='bat -p --color=always {}'"
export FZF_CTRL_R_OPTS="--style minimal --color 16 --info inline --no-sort --no-preview" # separate opts for history widget

# if running bash
# if [ -n "$BASH_VERSION" ]; then
#     [ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
# fi

# reserve tty1 for the xsessions
[ -z "$DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ] && exec startx "$XINITRC"

