# ~/.bashrc: executed by bash(1) for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# for setting history file. see HISTSIZE and HISTFILESIZE in bash(1)
HISTFILE=$HOME/.local/share/history
HISTSIZE=1000000000
HISTFILESIZE=1000000000

# Avoid duplicates & lines starting with space
# See bash(1) for more options
HISTCONTROL=erasedups:ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# Keep Bash history synchronized across all sessions:
# - history -n: read new lines from history file (other sessions)
# - history -w: write current session commands to history file
# - history -c: clear current in-memory history
# - history -r: reload history from file (merged with new lines)
PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"

# vim mode
# set -o vi

# Alias definitions.
ALIASRC="$XDG_CONFIG_HOME/shell/aliasrc"
if [ -f $ALIASRC ]; then
    . "$ALIASRC"
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# zoxide
eval "$(zoxide init bash)"

# pywal
export PATH="${PATH}:/home/zanzon/.local/share/pipx/venvs/pywal/lib/python3.13/site-packages"

# Import colorscheme from 'wal' asynchronously
# Not supported in the "fish" shell.
# (cat ~/.cache/wal/sequences &)

# To add support for TTYs this line can be optionally added.
# source ~/.cache/wal/colors-tty.sh

# Load dircolors
if [ -x /usr/bin/dircolors ]; then 
        test -r ~/.dir_colors && eval "$(dircolors -b ~/.dir_colors)" || eval "$(dircolors -b)"
fi

alias ls='ls --color=auto' 
#alias dir='dir --color=auto' 
#alias vdir='vdir --color=auto' 
alias grep='grep --color=auto' 
alias fgrep='fgrep --color=auto' 
alias egrep='egrep --color=auto' 


# Basic Prompt
export PS1='\[\e[1;34m\]\w\[\e[0m\] \[\e[1;32m\]>\[\e[0m\] '

# Fancy Prompt if you need it.
# export PS1='\n\[\e[1;37m\]┌─[\[\e[1;36m\]\u\[\e[1;37m\]@\[\e[1;35m\]\h\[\e[1;37m\]]-[\[\e[1;33m\]\w\[\e[1;37m\]]\n\[\e[1;37m\]└─[\[\e[1;32m\]\t\[\e[1;37m\]]\[\e[1;37m\]❯\[\e[0m\] '

# Key bindings
bind -x '"\C-r": READLINE_LINE=$(fzf_history); READLINE_POINT=${#READLINE_LINE}'
